-- Copyright 2026 agwlvssainokuni
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- U2 の利用者の表（UserAccount）。前進のみ・後方互換（1つ前の版のアプリは、この表を使わずにそのまま動く）。
--
-- email は前後の空白を除き小文字にそろえた値を保存し、一意とする（BR2.1、初期管理者の重複を防ぐ）。
-- password_hash は bcrypt の形式の文字列だけを保存し、平文は保存しない（BR1.5）。
-- 時刻はタイムゾーンに依存しない時点（UTC）として保存する。

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    admin_flag BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);
