/*
 * Copyright 2026 agwlvssainokuni
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package cherry.mastersmith.dslmanage.generate;

import static cherry.mastersmith.dslmanage.generate.GenerateTestSupport.INT;
import static cherry.mastersmith.dslmanage.generate.GenerateTestSupport.TEXT;
import static cherry.mastersmith.dslmanage.generate.GenerateTestSupport.VARCHAR_50;
import static cherry.mastersmith.dslmanage.generate.GenerateTestSupport.generate;
import static cherry.mastersmith.dslmanage.generate.GenerateTestSupport.notNull;
import static cherry.mastersmith.dslmanage.generate.GenerateTestSupport.nullable;
import static cherry.mastersmith.dslmanage.generate.GenerateTestSupport.schema;
import static cherry.mastersmith.dslmanage.generate.GenerateTestSupport.table;
import static cherry.mastersmith.dslmanage.generate.GenerateTestSupport.valid;
import static org.assertj.core.api.Assertions.assertThat;

import cherry.mastersmith.dsl.domain.DslColumn;
import cherry.mastersmith.dsl.domain.DslMenuItem;
import cherry.mastersmith.dsl.domain.DslModel;
import cherry.mastersmith.dsl.domain.DslTable;
import cherry.mastersmith.dsl.domain.FormPart;
import cherry.mastersmith.dsl.domain.ListFormat;
import cherry.mastersmith.dsl.domain.OptionSourceKind;
import cherry.mastersmith.dsl.domain.SearchOperator;
import cherry.mastersmith.dsl.domain.SortDirection;
import cherry.mastersmith.dsl.domain.Validation;
import cherry.mastersmith.dsl.domain.ValidationOrigin;
import cherry.mastersmith.dsl.domain.ValidationType;
import cherry.mastersmith.dsl.service.DslReader;
import cherry.mastersmith.dsl.validate.PatternChecker;
import cherry.mastersmith.targetdb.domain.DatabaseProduct;
import cherry.mastersmith.targetdb.domain.TargetColumn;
import cherry.mastersmith.targetdb.domain.TargetDbType;
import cherry.mastersmith.targetdb.domain.TargetForeignKey;
import cherry.mastersmith.targetdb.domain.TargetSchema;
import cherry.mastersmith.targetdb.domain.TargetTable;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.List;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * 組み立てと書き出しの単体テスト（BR1.2〜BR1.5・BR2.1〜BR2.5・BR3.1・BR3.2・BR4.1・BR5.1・BR5.3、NFR4.8・NFR4.9・NFR9.2、
 * AC1.1.1〜AC1.1.4 の生成の側）。生成した本文は U2 の本物の読み込みの口で検証する。
 */
class DslTreeBuilderTest {

    private static final PatternChecker PATTERNS = GenerateTestSupport.newPatternChecker();

    private static final DslReader READER = GenerateTestSupport.newReader(PATTERNS);

    @AfterAll
    static void close() {
        PATTERNS.close();
    }

    private static DslModel model(TargetSchema schema) {
        return valid(READER, generate(schema));
    }

    private static TargetSchema deptMst() {
        return schema(new TargetTable(
                "dept_mst",
                false,
                "部署",
                List.of(
                        new TargetColumn(
                                "dept_code",
                                new TargetDbType("varchar", 10L, null, null, "varchar(10)"),
                                false,
                                null,
                                "部署コード"),
                        new TargetColumn("note", new TargetDbType("text", null, null, null), true, null, null)),
                List.of("dept_code"),
                List.of()));
    }

    @Test
    @DisplayName("the example of the spec is generated byte for byte with the header comment and the fixed order")
    void exampleOfTheSpec() {
        byte[] yaml = generate(deptMst());

        assertThat(new String(yaml, StandardCharsets.UTF_8)).isEqualTo(GenerateTestSupport.expected("dept_mst.yaml"));
        assertThat(new String(yaml, StandardCharsets.UTF_8))
                .startsWith(DslYamlWriter.HEADER_COMMENT + "\nversion: 1\n")
                .doesNotContain("\r")
                .doesNotContain("!!")
                .doesNotContain("&id")
                .doesNotContain("*id");
        DslTable dept = valid(READER, yaml).tables().get("dept_mst");
        assertThat(dept.primaryKey()).containsExactly("dept_code");
        assertThat(dept.columns().keySet()).containsExactly("dept_code", "note");
    }

    @Test
    @DisplayName("labels use the comment for ja and the physical name for en, or the physical name for both")
    void labels() {
        DslModel model = model(schema(table(
                "emp",
                null,
                List.of("code"),
                List.of(),
                notNull("code", VARCHAR_50),
                new TargetColumn("name", VARCHAR_50, true, null, "氏名"))));

        DslTable emp = model.tables().get("emp");
        assertThat(emp.label()).isEqualTo(new cherry.mastersmith.dsl.domain.DisplayName("emp", "emp"));
        assertThat(emp.columns().get("name").label())
                .isEqualTo(new cherry.mastersmith.dsl.domain.DisplayName("氏名", "name"));
        assertThat(emp.columns().get("code").label())
                .isEqualTo(new cherry.mastersmith.dsl.domain.DisplayName("code", "code"));
        assertThat(model.menus())
                .singleElement()
                .satisfies(menu -> assertThat(menu.label()).isEqualTo(emp.label()));
    }

    @Test
    @DisplayName("control characters are removed from comments while line feeds, tabs and long comments stay")
    void controlCharactersInComments() {
        String longComment = "長".repeat(10_000);
        DslModel model = model(schema(table(
                "t\u0001",
                "表\u0000の\u007Fコメ\u0085ント\u009F\r",
                List.of(),
                List.of(),
                new TargetColumn("a", INT, true, null, "1行目\n2行目\tタブ"),
                new TargetColumn("b", INT, true, null, longComment),
                new TargetColumn("c", INT, true, null, "\u0007\u001B"))));

        DslTable table = model.tables().get("t\u0001");
        assertThat(table.label().ja()).isEqualTo("表のコメント");
        assertThat(table.label().en()).as("物理名は変えない").isEqualTo("t\u0001");
        assertThat(table.columns().get("a").label().ja()).isEqualTo("1行目\n2行目\tタブ");
        assertThat(table.columns().get("b").label().ja()).as("長さは切り詰めない").isEqualTo(longComment);
        assertThat(table.columns().get("c").label().ja())
                .as("制御文字だけのコメントは無いものとして物理名")
                .isEqualTo("c");
        assertThat(DslYamlWriter.stripControlCharacters(null)).isNull();
        assertThat(DslYamlWriter.stripControlCharacters(" \u0001 ")).isNull();
        assertThat(DslYamlWriter.stripControlCharacters(" 前後の空白 ")).isEqualTo(" 前後の空白 ");
    }

    @Test
    @DisplayName("a not-null string without default gets required and maxLength from the database")
    void validationsFromTheDatabase() {
        DslModel model = model(schema(table(
                "item",
                null,
                List.of(),
                List.of(),
                notNull("name", VARCHAR_50),
                new TargetColumn("status", VARCHAR_50, false, "'new'", null),
                nullable("memo", TEXT),
                notNull("qty", INT),
                nullable("huge", new TargetDbType("longtext", 4_294_967_295L, null, null, "longtext")))));

        DslTable item = model.tables().get("item");
        assertThat(item.columns().get("name").validations())
                .containsExactly(
                        new Validation(ValidationType.REQUIRED, null, null, ValidationOrigin.DB, null),
                        new Validation(
                                ValidationType.MAX_LENGTH, BigDecimal.valueOf(50), null, ValidationOrigin.DB, null));
        assertThat(item.columns().get("status").validations())
                .as("既定値のある NOT NULL は required にしない")
                .extracting(Validation::type)
                .containsExactly(ValidationType.MAX_LENGTH);
        assertThat(item.columns().get("memo").validations())
                .singleElement()
                .satisfies(v -> assertThat(v.number()).isEqualByComparingTo("65535"));
        assertThat(item.columns().get("qty").validations())
                .extracting(Validation::type)
                .as("数値の範囲は作らない")
                .containsExactly(ValidationType.REQUIRED);
        DslColumn huge = item.columns().get("huge");
        assertThat(huge.dbType().length()).as("DSL の整数の範囲を超える長さは無しにする").isNull();
        assertThat(huge.validations()).isEmpty();
    }

    @Test
    @DisplayName("menus and tables follow the physical names compared without case, then by the names themselves")
    void orderOfMenusAndTables() {
        DslModel model = model(schema(
                table("b_table", null, List.of(), List.of(), nullable("x", INT)),
                table("B", null, List.of(), List.of(), nullable("x", INT)),
                table("a_table", null, List.of(), List.of(), nullable("x", INT)),
                table("A_table", null, List.of(), List.of(), nullable("x", INT))));

        assertThat(model.menus()).extracting(DslMenuItem::table).containsExactly("A_table", "a_table", "B", "b_table");
        assertThat(model.tables().keySet()).containsExactly("A_table", "a_table", "B", "b_table");
        assertThat(DslTreeBuilder.NAME_ORDER.compare("b_table", "a_table")).isPositive();
        assertThat(DslTreeBuilder.NAME_ORDER.compare("a", "a")).isZero();
        assertThat(DslTreeBuilder.NAME_ORDER.compare("😀", "ａ"))
                .as("符号の順（サロゲートの組も1文字）")
                .isPositive();
    }

    @Test
    @DisplayName("a view is read-only without keys")
    void views() {
        TargetTable view = new TargetTable(
                "v_emp",
                true,
                null,
                List.of(nullable("id", INT), nullable("name", VARCHAR_50)),
                List.of(),
                List.of(new TargetForeignKey("fk", List.of("id"), "emp", List.of("id"))));
        DslModel model = model(schema(view, table("emp", null, List.of("id"), List.of(), notNull("id", INT))));

        DslTable table = model.tables().get("v_emp");
        assertThat(table.view()).isTrue();
        assertThat(table.primaryKey()).isEmpty();
        assertThat(table.foreignKeys()).isEmpty();
        assertThat(table.columns().get("id").formPart()).isEqualTo(FormPart.NUMBER);
    }

    @Test
    @DisplayName("a single column foreign key becomes a select with reference options, a composite one is only copied")
    void foreignKeys() {
        TargetTable dept = table(
                "dept", "部署", List.of("code", "sub"), List.of(), notNull("code", VARCHAR_50), notNull("sub", INT));
        TargetTable emp = table(
                "emp",
                null,
                List.of("id"),
                List.of(
                        new TargetForeignKey("fk_dept", List.of("dept_code"), "dept", List.of("code")),
                        new TargetForeignKey(
                                "fk_pair", List.of("pair_code", "pair_sub"), "dept", List.of("code", "sub")),
                        new TargetForeignKey("fk_self", List.of("id"), "emp", List.of("id")),
                        new TargetForeignKey("fk_hidden", List.of("hidden_ref"), "not_readable", List.of("id")),
                        new TargetForeignKey("fk_hidden_col", List.of("hidden_col"), "dept", List.of("secret"))),
                notNull("id", INT),
                nullable("dept_code", VARCHAR_50),
                nullable("pair_code", VARCHAR_50),
                nullable("pair_sub", INT),
                nullable("hidden_ref", INT),
                nullable("hidden_col", INT));
        DslModel model = model(schema(emp, dept));

        DslTable table = model.tables().get("emp");
        DslColumn deptCode = table.columns().get("dept_code");
        assertThat(deptCode.formPart()).isEqualTo(FormPart.SELECT);
        assertThat(deptCode.search().operator()).isEqualTo(SearchOperator.CHOICE);
        assertThat(deptCode.options().source()).isEqualTo(OptionSourceKind.REFERENCE);
        assertThat(deptCode.options().table()).isEqualTo("dept");
        assertThat(deptCode.options().valueColumn()).isEqualTo("code");
        assertThat(deptCode.options().labelColumn()).isEqualTo("code");
        assertThat(table.columns().get("pair_code").formPart()).isEqualTo(FormPart.TEXT);
        assertThat(table.columns().get("pair_sub").formPart()).isEqualTo(FormPart.NUMBER);
        assertThat(table.columns().get("pair_code").options()).isNull();
        DslColumn id = table.columns().get("id");
        assertThat(id.formPart()).as("主キーを兼ねる外部キーも select").isEqualTo(FormPart.SELECT);
        assertThat(id.search().operator()).isEqualTo(SearchOperator.CHOICE);
        assertThat(table.foreignKeys())
                .as("参照先が写しに無い外部キーは写さない")
                .hasSize(3)
                .extracting(fk -> fk.columns())
                .containsExactly(List.of("dept_code"), List.of("pair_code", "pair_sub"), List.of("id"));
        assertThat(table.columns().get("hidden_ref").formPart()).isEqualTo(FormPart.NUMBER);
        assertThat(table.columns().get("hidden_col").options()).isNull();
    }

    @Test
    @DisplayName("search, list, detail and format follow the category and the primary key")
    void initialSettings() {
        DslModel model = model(schema(table(
                "t",
                null,
                List.of("id"),
                List.of(),
                notNull("id", INT),
                nullable("memo", TEXT),
                nullable("geo", new TargetDbType("geometry", null, null, null, "geometry")),
                nullable("flag", new TargetDbType("tinyint", null, 3, 0, "tinyint(1)")),
                nullable("born", new TargetDbType("date", null, null, null)),
                nullable("at", new TargetDbType("datetime", null, null, null)),
                nullable("hm", new TargetDbType("time", null, null, null)),
                nullable("name", VARCHAR_50))));

        DslTable t = model.tables().get("t");
        DslColumn id = t.columns().get("id");
        assertThat(id.search().operator()).as("主キーは EQUALS").isEqualTo(SearchOperator.EQUALS);
        assertThat(id.list().order()).isEqualTo(1);
        assertThat(id.list().defaultSort()).isEqualTo(SortDirection.ASC);
        assertThat(id.list().format()).isEqualTo(ListFormat.NUMBER_GROUPED);
        DslColumn memo = t.columns().get("memo");
        assertThat(memo.list().visible()).isFalse();
        assertThat(memo.list().order()).isNull();
        assertThat(memo.list().sortable()).isFalse();
        assertThat(memo.detail().visible()).isTrue();
        DslColumn geo = t.columns().get("geo");
        assertThat(geo.formPart()).isEqualTo(FormPart.TEXT);
        assertThat(geo.search().enabled()).isFalse();
        assertThat(geo.search().operator()).isNull();
        assertThat(geo.list().visible()).isFalse();
        assertThat(geo.detail().visible()).isFalse();
        assertThat(geo.dbType().name()).as("DB 上の型はそのまま").isEqualTo("geometry");
        DslColumn flag = t.columns().get("flag");
        assertThat(flag.formPart()).isEqualTo(FormPart.CHECKBOX);
        assertThat(flag.search().operator()).isEqualTo(SearchOperator.CHOICE);
        assertThat(flag.list().format()).isEqualTo(ListFormat.BOOLEAN_YES_NO);
        assertThat(flag.dbType().name()).as("型の名前は DATA_TYPE のまま").isEqualTo("tinyint");
        assertThat(flag.dbType().precision()).isEqualTo(3);
        assertThat(t.columns().get("born").formPart()).isEqualTo(FormPart.DATE);
        assertThat(t.columns().get("at").formPart()).isEqualTo(FormPart.DATETIME);
        assertThat(t.columns().get("hm").formPart()).isEqualTo(FormPart.TEXT);
        assertThat(t.columns().get("hm").search().operator()).isEqualTo(SearchOperator.EQUALS);
        assertThat(t.columns().get("hm").list().format()).isEqualTo(ListFormat.TIME);
        assertThat(t.columns().values())
                .filteredOn(column -> column.list().visible())
                .extracting(column -> column.list().order())
                .as("表示するカラムに定義の順で 1 から")
                .containsExactly(1, 2, 3, 4, 5, 6);
        assertThat(t.columns().values())
                .filteredOn(column -> !column.name().equals("id"))
                .extracting(column -> column.list().defaultSort())
                .containsOnlyNulls();
    }

    @Test
    @DisplayName("no default sort without a primary key or when the first key column is not listed")
    void noDefaultSort() {
        DslModel model = model(schema(
                table("no_key", null, List.of(), List.of(), notNull("id", INT)),
                table("text_key", null, List.of("body", "id"), List.of(), notNull("body", TEXT), notNull("id", INT))));

        assertThat(model.tables().get("no_key").columns().get("id").list().defaultSort())
                .isNull();
        assertThat(model.tables().get("text_key").columns().values())
                .extracting(column -> column.list().defaultSort())
                .containsOnlyNulls();
        assertThat(model.tables().get("text_key").columns().get("body").search().operator())
                .isEqualTo(SearchOperator.EQUALS);
    }

    @Test
    @DisplayName("names and comments with YAML symbols keep their values and never become tags or aliases")
    void yamlSymbols() {
        List<String> names = List.of(
                "<<", "null", "~", "yes", "No", "123", "1e3", "!!str x", "&a", "*a", "# x", "- x", ": x", "'", "\"",
                "a: b", "[x]", "{x}", "|", ">", "%x", "@x", "`x`", " lead", "trail ", "日本語");
        TargetColumn[] columns = names.stream()
                .map(name -> new TargetColumn(name, VARCHAR_50, true, null, name + " !!binary &x *y"))
                .toArray(TargetColumn[]::new);
        byte[] yaml = generate(schema(table("!!python/object", "#", List.of(), List.of(), columns)));

        DslTable table = valid(READER, yaml).tables().get("!!python/object");
        assertThat(table.label().ja()).isEqualTo("#");
        assertThat(table.columns().keySet()).containsExactlyElementsOf(names);
        for (String name : names) {
            assertThat(table.columns().get(name).label().ja()).isEqualTo(name + " !!binary &x *y");
        }
    }

    @Test
    @DisplayName("no value outside the schema copy such as the schema name or connection settings is written")
    void nothingOutsideTheCopy() {
        String schemaName = "schema_name_not_in_dsl";
        TargetSchema schema = new TargetSchema(
                DatabaseProduct.POSTGRESQL,
                schemaName,
                List.of(table("emp", null, List.of("id"), List.of(), notNull("id", INT))));

        String yaml = new String(generate(schema), StandardCharsets.UTF_8);

        assertThat(yaml)
                .doesNotContain(schemaName)
                .doesNotContainIgnoringCase("jdbc:")
                .doesNotContainIgnoringCase("password")
                .doesNotContainIgnoringCase("user")
                .doesNotContainIgnoringCase("host")
                .doesNotContainIgnoringCase("postgres");
    }

    @Test
    @DisplayName("a schema without tables gives empty menus and tables that pass the validation")
    void emptySchema() {
        byte[] yaml = generate(schema());

        assertThat(new String(yaml, StandardCharsets.UTF_8))
                .isEqualTo(DslYamlWriter.HEADER_COMMENT + "\nversion: 1\nmenus: []\ntables: {}\n");
        DslModel model = valid(READER, yaml);
        assertThat(model.menus()).isEmpty();
        assertThat(model.tables()).isEmpty();
    }
}
