-- Copyright 2026 agwlvssainokuni
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- Intent 261004-role-menu の U3（グループとメンバーの管理）。前進のみ・後方互換（BR8.8、NFR3.6）。
-- 適用済みの V1〜V9 は書き換えない。既存の表と行は変えず、グループの表・メンバーの表を新しく足し、監査イベントの表に3列を足す
-- （広げてから縮める二段の「広げる」側だけ）。1つ前の版のアプリは足した表と列を読まないため、そのまま起動できる。
--
-- groups の列:
--   name: GroupName の規則で正規化した名前（前後の空白を取り除き、コードポイントで 1〜64、制御文字なし。BR1.1〜BR1.3）。
--     列の長さは UTF-16 の 128 単位（64 コードポイントがすべてサロゲートペアでも収まる）。
--   name_key: 名前を言語に依らない小文字にした、大文字と小文字を区別しない比べのための値。アプリの GroupName だけが作り、通常の列に
--     保存する（DB の生成列にしない。BR1.4）。全角と半角は変換しない。列の長さは UTF-16 の 256 単位（小文字化で文字が増える分を
--     見込む）。
--   created_at・updated_at: UTC の時点。updated_at は名前の変更で更新し、メンバーの足し外しでは変えない。
-- group_members の列:
--   group_id・user_id の組が主キー（重ねての追加は GROUP_NO_CHANGE。BR3.3・BR5.5）。added_at は詳細のメンバーの並びに使う（BR7.4）。
-- 制約と索引（名前は store の区分が違反の読み替え先を決めるのに使う。変えない）:
--   uk_groups_name_key: 名前の鍵の一意（大文字と小文字だけが違う名前は同じ名前）。
--   pk_group_members: メンバーの組の一意。
--   fk_group_members_group: 消えたグループを指すメンバーを作らない最後の守り（削除の制限。BR5.4）。
--   fk_group_members_user: 登録の終わった利用者（users の行）だけを指す（BR3.1）。
--   ix_group_members_user_id: 利用者が属するグループの読み取り（groupIdsOfUser）を1回の読み取りに収める（主キーの先頭は group_id
--     のため、user_id だけの絞り込みに効かない）。
--
-- audit_events に足す列（契約 C10。U4 role も同じ列を使う）。空を許し、既定値・参照の制約・索引を置かない（V6・V7 と同じ形。追記
-- だけの記録で、グループの削除の後も監査の行は残る）:
--   target_role_id: 対象のロール（U3 では使わない）。
--   target_group_id: 対象のグループ。
--   detail: 決めた型から作る JSON の文字列。上限は UTF-16 の 16,384 単位で、超える値はアプリが作らない（切り詰めない。BR8.6）。
--     メールアドレス・氏名・パスワード・トークンを入れない（BR8.7）。
--
-- H2 は DDL を巻き戻せないため、途中で失敗すると一部だけ当たった状態が残りうる。失敗したときは Flyway が起動を止め、配備の前の
-- バックアップから戻す（README の「戻し方」）。

CREATE TABLE groups (
    group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    name_key VARCHAR(256) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_groups_name_key UNIQUE (name_key)
);

CREATE TABLE group_members (
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    added_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_group_members PRIMARY KEY (group_id, user_id)
);

ALTER TABLE group_members
    ADD CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (group_id) ON DELETE RESTRICT;

ALTER TABLE group_members
    ADD CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users (user_id);

CREATE INDEX ix_group_members_user_id ON group_members (user_id);

ALTER TABLE audit_events ADD COLUMN target_role_id BIGINT;
ALTER TABLE audit_events ADD COLUMN target_group_id BIGINT;
ALTER TABLE audit_events ADD COLUMN detail VARCHAR(16384);
