-- Copyright 2026 agwlvssainokuni
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- Intent 261004-role-menu の U4（ロールと権限の設定。Bolt B4）。前進のみ・後方互換（NFR3.6）。
-- 適用済みの V1〜V10 は書き換えない。既存の表と行は変えず、ロールの表と権限の設定の表を新しく足すだけ（広げてから縮める二段の
-- 「広げる」側だけ）。users.admin_flag は残し、行を移さない（管理の可否は今までどおり admin_flag で決める）。1つ前の版のアプリは
-- 足した表を読まないため、そのまま起動できる。監査イベントの表には列を足さない（V10 の target_role_id・target_group_id・detail を使う）。
--
-- roles の列:
--   name: RoleName の規則で正規化した名前（前後の空白を取り除き、コードポイントで 1〜64、制御文字なし。BR1.1〜BR1.3）。
--     列の長さは UTF-16 の 128 単位（64 コードポイントがすべてサロゲートペアでも収まる）。
--   name_key: 名前を言語に依らない小文字にした、大文字と小文字を区別しない比べのための値。アプリの RoleName だけが作り、通常の列に
--     保存する（DB の生成列にしない。BR1.4）。全角と半角は変換しない。列の長さは UTF-16 の 256 単位（小文字化で文字が増える分を
--     見込む）。
--   created_at・updated_at: UTC の時点。updated_at は名前の変更・権限の保存・消す・import の置き換えで更新する。
-- permission_settings の列（ロールの1つの対象への明示の設定。少なくとも1つの値が設定されている対象だけ行を持つ。BR4.2）:
--   schema_name・table_name・column_name: 対象の名前（DSL の名前。大文字と小文字を区別する。BR4.3）。下位の名前の無い階層は空の
--     文字列（DSL の名前は1文字以上のため実の名前と重ならない）。名前はコードポイントで 1〜128 のため、列は UTF-16 の 256 単位。
--     DSL への参照は持たない（今の DSL に無い対象の設定も名前で残る。ADR-004）。
--   main_permission: 主権限（NONE・READ・FULL）。NULL は「設定なし」。
--   create_permission・delete_permission: 補助権限。NULL は「設定なし」、TRUE は可、FALSE は不可。カラムの行は必ず NULL。
--   updated_at: UTC の時点。
-- 制約と索引（名前は store の区分が違反の読み替え先を決めるのに使う。変えない）:
--   uk_roles_name_key: 名前の鍵の一意（大文字と小文字だけが違う名前は同じ名前）。
--   pk_permission_settings: ロールと対象の名前の組の一意。主キーの先頭（ロール・スキーマ・テーブル）で木の1階層の範囲を読む。
--   fk_permission_settings_role: 消えたロールを指す設定を作らない（削除の制限。ロールの削除は同じトランザクションで先に設定を消す。
--     BR3.3）。
--   ck_permission_settings_any: 3つの値の少なくとも1つが設定されている（全部が設定なしの行は持たない。BR4.2）。
--   ck_permission_settings_level: table_name が空なら column_name も空（カラムの階層はテーブルの下だけ）。
--   ck_permission_settings_column_aux: カラムの行は補助権限を持たない（BR4.1）。
--   ck_permission_settings_main: 主権限の値は NONE・READ・FULL のどれか（NULL は設定なし）。
--
-- H2 は DDL を巻き戻せないため、途中で失敗すると一部だけ当たった状態が残りうる。失敗したときは Flyway が起動を止め、配備の前の
-- バックアップから戻す（README の「戻し方」）。

CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    name_key VARCHAR(256) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_roles_name_key UNIQUE (name_key)
);

CREATE TABLE permission_settings (
    role_id BIGINT NOT NULL,
    schema_name VARCHAR(256) NOT NULL,
    table_name VARCHAR(256) DEFAULT '' NOT NULL,
    column_name VARCHAR(256) DEFAULT '' NOT NULL,
    main_permission VARCHAR(8),
    create_permission BOOLEAN,
    delete_permission BOOLEAN,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_permission_settings PRIMARY KEY (role_id, schema_name, table_name, column_name),
    CONSTRAINT ck_permission_settings_any
        CHECK (main_permission IS NOT NULL OR create_permission IS NOT NULL OR delete_permission IS NOT NULL),
    CONSTRAINT ck_permission_settings_level CHECK (table_name <> '' OR column_name = ''),
    CONSTRAINT ck_permission_settings_column_aux
        CHECK (column_name = '' OR (create_permission IS NULL AND delete_permission IS NULL)),
    CONSTRAINT ck_permission_settings_main
        CHECK (main_permission IS NULL OR main_permission IN ('NONE', 'READ', 'FULL'))
);

ALTER TABLE permission_settings
    ADD CONSTRAINT fk_permission_settings_role FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE RESTRICT;
