-- Copyright 2026 agwlvssainokuni
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- U2 の認証の表（Authentication）。前進のみ・後方互換（1つ前の版のアプリは、これらの表を使わずにそのまま動く）。
-- 時刻はタイムゾーンに依存しない時点（UTC）として保存する。

-- ロックの状態。利用者の行は subject_id = users.user_id（利用者の作成と同じトランザクションで作る）。
-- 存在しないメールアドレスの試みは、利用者と結びつかないダミーの行（負の ID）に同じ読み書きを行う（BR2.7、BR3.9）。
-- ダミーの行を同じ表に置くため、users への外部キーは置かない（同じ SQL で読み書きし、回数と種類をそろえる）。
CREATE TABLE login_attempt_states (
    subject_id BIGINT PRIMARY KEY,
    consecutive_failures INT NOT NULL,
    locked_until TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_login_attempt_states_failures CHECK (consecutive_failures >= 0)
);

-- ダミーの行（8 行）。利用者の ID（1 以上の自動採番）と重ならない。
INSERT INTO login_attempt_states (subject_id, consecutive_failures, locked_until) VALUES
    (-1, 0, NULL),
    (-2, 0, NULL),
    (-3, 0, NULL),
    (-4, 0, NULL),
    (-5, 0, NULL),
    (-6, 0, NULL),
    (-7, 0, NULL),
    (-8, 0, NULL);

-- リフレッシュトークン。値は保存せず、SHA-256 のハッシュ（32 バイト）だけを保存する（BR5.1）。
-- ログインのたびに新しい行を作り（BR5.7）、無効化は revoked_at を設定する（BR5.4、BR6.1）。
CREATE TABLE refresh_tokens (
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash BINARY(32) NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash)
);

-- 使い終わったトークンの削除（期限で探す）と、利用者ごとの探索のための索引。
CREATE INDEX ix_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (user_id);
