-- Copyright 2026 agwlvssainokuni
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- U4（Intent 260923-dsl-schema-loader の DSL の管理）のプレビューと適用の履歴の表。前進のみ・後方互換
-- （表を足すだけで、1つ前の版のアプリはこれらの表を使わずにそのまま動く）。
-- 時刻はタイムゾーンに依存しない時点（UTC）として保存する。
--
-- DSL の本文は受け取ったバイト列のまま BINARY LARGE OBJECT に入れる（識別とダウンロードがバイト単位で一致する。NFR 設計 Q3: A）。
-- 本文の大きさの上限は 10MB（投入の要求の本文の上限で守る）。プレビュー1件と履歴 20 件がすべて 10MB なら最大約 210MB。
-- 置いた人・適用した人は利用者の ID だけを持つ。利用者の表への外部キーは置かない（今の状態・履歴では、利用者が見つからなければ
-- 「不明」として示す。BR6.3）。

-- プレビュー（最大1行、管理者全員で共有）。行の鍵を固定の値 1 にし、置き換えは1文の MERGE で行う（BR1.4）。
-- preview_id は置くたびに新しく振り、適用の要求はこの値で今のプレビューを指す（BR4.1・BR4.3）。
CREATE TABLE dsl_previews (
    preview_slot INTEGER PRIMARY KEY,
    preview_id UUID NOT NULL,
    yaml_bytes BINARY LARGE OBJECT NOT NULL,
    dsl_hash VARCHAR(64) NOT NULL,
    source VARCHAR(16) NOT NULL,
    placed_by_user_id BIGINT NOT NULL,
    placed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_dsl_previews_slot CHECK (preview_slot = 1),
    CONSTRAINT ck_dsl_previews_source CHECK (source IN ('GENERATED', 'UPLOAD', 'PASTE', 'RESTORE')),
    CONSTRAINT uk_dsl_previews_preview_id UNIQUE (preview_id)
);

-- 適用の履歴。追加の順（sequence_no、DB の連番）が一意で、件数の上限を超えたら古いものから消す（BR4.4）。
-- 適用中の DSL は、適用した日時が最も新しい1件（同じ日時なら追加の順）。
CREATE TABLE dsl_applied_revisions (
    sequence_no BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id UUID NOT NULL,
    yaml_bytes BINARY LARGE OBJECT NOT NULL,
    dsl_hash VARCHAR(64) NOT NULL,
    source VARCHAR(16) NOT NULL,
    applied_by_user_id BIGINT NOT NULL,
    applied_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_dsl_applied_revisions_source CHECK (source IN ('GENERATED', 'UPLOAD', 'PASTE', 'RESTORE')),
    CONSTRAINT uk_dsl_applied_revisions_revision_id UNIQUE (revision_id)
);
