-- Copyright 2026 agwlvssainokuni
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- Intent 260925-user-management の U3（招待と登録の完了）。前進のみ・後方互換（BR11.3、NFR10.1〜NFR10.3）。
-- 適用済みの V1〜V7 は書き換えない。既存の表は変えず、招待の表 invitations を新しく足す（ADR-001）。
-- 1つ前の版のアプリは招待の表を読まないため、そのまま起動できる。
--
-- 列:
--   email: 前後の空白を除き小文字にそろえた招待先のメールアドレス（users.email と同じ長さ）。
--   language: 招待の言語（ja・en）。値の決まりはアプリの純粋な関数で守る（CHECK の制約は置かない。V7 と同じ考え方）。
--   token_hash: 招待のトークンの SHA-256（32 バイト）だけ。トークンそのものは保存しない（project.md の Mandated）。
--   send_result: 招待メールの送信の結果（PENDING・SENT・FAILED）。PENDING は送信中・結果不明で、API では FAILED として返す。
--   state: 招待の状態（PENDING・COMPLETED・CANCELLED・REPLACED）。期限切れは保存せず、時計で決める。
--   ended_at: PENDING から終わった状態に移った時点（保存期間の起点）。completed_user_id: 登録の完了で作った利用者。
--   pending_email: state が PENDING のときだけ email、それ以外は空（NULL）になる生成列。アプリは書かない（エンティティにも無い）。
-- 制約:
--   uk_invitations_pending_email: 同じメールアドレスの PENDING を常に1件に限る（BR2.5、reliability-design.md 2.1）。H2 は条件つきの
--     一意の索引を持たないため生成列に一意の制約を付ける。一意の制約は空を重ねてよいため、終わった招待はいくつでも残せる。
--   uk_invitations_token_hash: トークンのハッシュはすべての行で一意。
--   招待した管理者と完了した利用者は users への参照を持つ。監査の記録（audit_events.target_invitation_id）からは参照の制約を
--   置かない（招待の行が定期の削除で消えても監査の記録は残る）。
--
-- H2 は DDL を巻き戻せないため、途中で失敗すると一部だけ当たった状態が残りうる。失敗したときは Flyway が起動を止め、配備の前の
-- バックアップから戻す（README の「戻し方」）。

CREATE TABLE invitations (
    invitation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    language VARCHAR(2) NOT NULL,
    token_hash BINARY(32) NOT NULL,
    invited_by_user_id BIGINT NOT NULL,
    invited_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    send_result VARCHAR(8) NOT NULL,
    state VARCHAR(16) NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE,
    completed_user_id BIGINT,
    pending_email VARCHAR(254) GENERATED ALWAYS AS (CASE WHEN state = 'PENDING' THEN email END),
    CONSTRAINT uk_invitations_token_hash UNIQUE (token_hash),
    CONSTRAINT uk_invitations_pending_email UNIQUE (pending_email),
    CONSTRAINT ck_invitations_state CHECK (state IN ('PENDING', 'COMPLETED', 'CANCELLED', 'REPLACED')),
    CONSTRAINT ck_invitations_send_result CHECK (send_result IN ('PENDING', 'SENT', 'FAILED'))
);

ALTER TABLE invitations
    ADD CONSTRAINT fk_invitations_invited_by FOREIGN KEY (invited_by_user_id) REFERENCES users (user_id);

ALTER TABLE invitations
    ADD CONSTRAINT fk_invitations_completed_user FOREIGN KEY (completed_user_id) REFERENCES users (user_id);
