-- Copyright 2026 agwlvssainokuni
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- U4 の監査イベントの表（AuditLog）。前進のみ・後方互換（1つ前の版のアプリは、この表を使わずにそのまま動く）。
-- 時刻はタイムゾーンに依存しない時点（UTC）として保存する。
--
-- 追記だけの表であり、アプリは変更・削除の処理を持たない（BR4.1、NFR3.2）。
-- 主キーは DB の連番とし、追記の前に読み取りをしない（NFR1.3）。
-- 文字列の列の長さは、切り詰めの上限（コードポイント単位: メールアドレス 254、User-Agent 512、要求のパス 512）の
-- 2倍とする。VARCHAR(n) は Java の文字数で数えるため、サロゲートペア（絵文字など）を含む値は上限の2倍の長さになりうる。

CREATE TABLE audit_events (
    audit_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    result VARCHAR(16) NOT NULL,
    entered_email VARCHAR(508),
    failure_reason VARCHAR(32),
    source_ip VARCHAR(45) NOT NULL,
    user_agent VARCHAR(1024),
    request_path VARCHAR(1024),
    trace_id VARCHAR(64)
);

-- 後続Intentで監査ログを見る画面を作るときの、日時での絞り込みに備える索引。
-- 追記の費用を増やさないため、索引はこの1つだけにする（NFR1.5）。
CREATE INDEX ix_audit_events_occurred_at ON audit_events (occurred_at);
